name: Unit test

on:
  push:
    branches:
      - master
      - next
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn bootstrap
      - run: yarn build
      - run: yarn test
        env:
          CI: true
